# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Residencial Eco Quality
email: admin@ecoquality.com.br
description: > # this means to ignore newlines until "baseurl:"
  Loteamento de alto padrão, belíssima área de lazer, lotes apartir de 400 metros, tudo isso em um lugar privilegiado, venham conferir!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ecoquality.com.br" # the base hostname & protocol for your site
twitter_username: fernandokobayas
github_username:  fmkoba

# Build settings
markdown: kramdown
